#  Template python-build

#  This template allows you to validate your python code.
#  The workflow allows running tests and code linting on the default branch.

image: continuumio/miniconda3:latest

pipelines:
  default:
    - step:
        name: Test
        caches:
          - pip
        script:
          - pip install pytest
          - pytest 
